### ISSUE TITLE
files mv'd into vent_files are not triggering file-drop

### ISSUE THREAD

**Issue by tdutty** [CyberReboot/vent#1212] opened 2018-11-12 21:36 UTC

**Comment by tdutty** [comment] 2018-11-12 21:38
The vent.log files is giving a false output for the vent.api.plugin: 734,  container health status for elasticsearch:master is always 'starting'.

**Comment by cglewis** [comment] 2018-11-12 21:44
the title and comment seem like two different issues, no? which issue are you running into?

**Comment by tdutty** [comment] 2018-11-12 22:02
I'm looking for the source of the issue, it could be a multitude of problems.  When I launched the vent instances, and attempted to copy a file into the directory, the plugins pointed aren't triggered. When I look through the vent.logs it returns- vent.api.plugins:734  - INFO - Status of _build_image: False. When I check the docker containers associated with the vent cores, I notice that one of the containers health status is starting or restarting but never healthy. I thought the issues were related. I've been following toying with it for a while but I can't seem to find a solution, I don't think its docker or the permissions, the daemon is running. My python is libraries are up-to-date. I'm not sure what the cause, maybe the plugin is out-of-date. I'm using the vent plugin for bulk indexing json files into elasticsearch servers.

**Comment by rashley-iqt** [comment] 2018-11-13 16:34
Can you send us your full vent logs?

**Comment by tdutty** [comment] 2018-11-14 00:34
Sure, this is Dropbox link to the log : https://www.dropbox.com/s/yz0bs9izhxg6jnn/vent.log?dl=0

**Comment by cglewis** [comment] 2018-11-20 18:37
Do you have a `/var/log/vent/cyberreboot-vent-rmq-es-connector-master.log`? If so can you send us that as well?  That will tell if the messages from the plugin are getting sent to Elastic or not.

**Comment by tdutty** [comment] 2018-11-20 20:49
https://www.dropbox.com/s/fs38l84zhcklnu9/cyberreboot-vent-rmq-es-connector-master.log?dl=0

**Comment by tdutty** [comment] 2018-11-20 20:49
> Do you have a `/var/log/vent/cyberreboot-vent-rmq-es-connector-master.log`? If so can you send us that as well? That will tell if the messages from the plugin are getting sent to Elastic or not.

https://www.dropbox.com/s/fs38l84zhcklnu9/cyberreboot-vent-rmq-es-connector-master.log?dl=0

**Comment by cglewis** [comment] 2018-11-20 21:09
ah, looks like RMQ isn't able to talk to Elasticsearch from your logs:

```
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: PUT http://elasticsearch:9200/cyberreboot-vent-elasticsearch-master/cyberreboot-vent-elasticsearch-master/syslog.cyberreboot-vent-elasticsearch-master.ip-172-31-12-228.1542105415.92be9b6d-e695-479e-802f-845ee976bfbe [status:N/A request:3.000s]
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: Traceback (most recent call last):
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     (self._dns_host, self.port), self.timeout, **extra_kw)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     raise err
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     sock.connect(sa)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: OSError: [Errno 113] Host is unreachable
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: 
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: During handling of the above exception, another exception occurred:
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: 
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: Traceback (most recent call last):
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     _stacktrace=sys.exc_info()[2])
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     raise six.reraise(type(error), error, _stacktrace)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     raise value
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     chunked=chunked)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     conn.request(method, url, **httplib_request_kw)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/http/client.py", line 1239, in request
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     self._send_request(method, url, body, headers, encode_chunked)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     self.endheaders(body, encode_chunked=encode_chunked)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     self._send_output(message_body, encode_chunked=encode_chunked)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     self.send(msg)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/http/client.py", line 964, in send
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     self.connect()
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     conn = self._new_conn()
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]:     self, "Failed to establish a new connection: %s" % e)
2018-11-13T11:07:49+00:00 172.17.0.1 cyberreboot-vent-rmq-es-connector-master[1611]: urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fc9b6a8d940>: Failed to establish a new connection: [Errno 113] Host is unreachable
```

I've been able to reproduce this on my end, will work on a fix and update you here.

**Comment by cglewis** [comment] 2018-11-27 16:37
working on a rollback, but looks like it's being caused by this: https://github.com/rq/rq/issues/1014

**Comment by cglewis** [comment] 2018-11-28 04:39
A fix has been pushed up for the rq issue. @tdutty if you could try again that would be great. It's not a supported plugin that you're trying, but it should work.

**Comment by cglewis** [comment] 2018-12-10 15:53
Closing as a fix has been pushed for this. Please reopen if you're still experiencing the issue. Thanks!

**Closed by cglewis** 2018-12-10 15:53 UTC
